import { useLivePlayerInitializer } from "./useLivePlayerInitializer.js";
import { useLiveReplayPlayback } from "./useLiveReplayPlayback.js";

function createReplayPlayback(ctx, getInitVideoPlayer) {
  return useLiveReplayPlayback({
    replayFutureStartTimerRef: ctx.replayFutureStartTimerRef,
    replayVideosList: ctx.replayVideosList,
    replayCurrentIndex: ctx.replayCurrentIndex,
    replayCurrentVideoId: ctx.replayCurrentVideoId,
    replayLoopPlay: ctx.replayLoopPlay,
    replayLastTime: ctx.replayLastTime,
    isReplay: ctx.isReplay,
    isPlaying: ctx.isPlaying,
    pullUrl: ctx.pullUrl,
    videoUrl: ctx.videoUrl,
    replayProductSchedule: ctx.replayProductSchedule,
    scheduleExplainActiveId: ctx.scheduleExplainActiveId,
    messages: ctx.messages,
    clearCommentQueue: ctx.clearCommentQueue,
    refreshPinnedMessage: ctx.refreshPinnedMessage,
    productList: ctx.productList,
    showProduct: ctx.showProduct,
    explainingProductId: ctx.explainingProductId,
    currentProduct: ctx.currentProduct,
    getVideoPlayer: ctx.getVideoPlayer,
    setVideoPlayer: ctx.setVideoPlayer,
    getLiveVideoElement: ctx.getLiveVideoElement,
    initVideoPlayer: (...args) => getInitVideoPlayer()(...args),
    loadCommentHistory: ctx.loadCommentHistory,
    loadCurrentProduct: ctx.loadCurrentProduct,
    liveId: ctx.liveId,
    roomCode: ctx.roomCode,
    liveTenantId: ctx.liveTenantId,
    shareCode: ctx.shareCode,
    liveBindId: ctx.liveBindId,
    myUserId: ctx.myUserId,
    roomGroupType: ctx.roomGroupType,
    roomWatchByDay: ctx.roomWatchByDay,
    pushStatus: ctx.pushStatus,
    stopHeartbeat: ctx.stopHeartbeat,
    persistReplayProgress: ctx.persistReplayProgress,
    roomCurrentTermId: ctx.roomCurrentTermId,
    syncLiveMiniWindowState: ctx.syncLiveMiniWindowState,
    syncReplayCommentCursor: ctx.syncReplayCommentCursor,
    enqueueReplayComments: ctx.enqueueReplayComments,
    replayCommentCursor: ctx.replayCommentCursor,
    replayCommentTimeline: ctx.replayCommentTimeline,
    replaceReplayMessagesAt: ctx.replaceReplayMessagesAt,
    mapProductItem: ctx.mapProductItem,
    syncProductCardIndex: ctx.syncProductCardIndex,
    incrementProductHotOrder: ctx.incrementProductHotOrder,
    showBuyingNotice: ctx.showBuyingNotice,
    formatLiveNickname: ctx.formatLiveNickname,
    reportViewProgressApi: ctx.reportViewProgressApi,
    scheduleExplainTimerRef: ctx.scheduleExplainTimerRef,
    setVideoDebugActualCaptured: ctx.setVideoDebugActualCaptured,
    videoDebugInfo: ctx.videoDebugInfo,
    currentVideoPoster: ctx.currentVideoPoster,
    liveCover: ctx.liveCover,
    isMuted: ctx.isMuted,
    videoFrameReady: ctx.videoFrameReady,
    quickReplies: ctx.quickReplies,
  });
}

function createPlayerInitializer(ctx, replayPlayback) {
  return useLivePlayerInitializer({
    videoUrl: ctx.videoUrl,
    pullUrl: ctx.pullUrl,
    videoRenderKey: ctx.videoRenderKey,
    syncLiveMiniWindowState: ctx.syncLiveMiniWindowState,
    replayLastTime: ctx.replayLastTime,
    videoDebugInfo: ctx.videoDebugInfo,
    getVideoDebugActualCaptured: ctx.getVideoDebugActualCaptured,
    setVideoDebugActualCaptured: ctx.setVideoDebugActualCaptured,
    getLiveVideoElement: ctx.getLiveVideoElement,
    applyInlineVideoAttrs: ctx.applyInlineVideoAttrs,
    getVideoPlayer: ctx.getVideoPlayer,
    setVideoPlayer: ctx.setVideoPlayer,
    autoplayBlocked: ctx.autoplayBlocked,
    isPlaying: ctx.isPlaying,
    videoFrameReady: ctx.videoFrameReady,
    isMuted: ctx.isMuted,
    onVideoTimeUpdate: (...args) => replayPlayback.onVideoTimeUpdate(...args),
    getSrcSwitchGuard: () => replayPlayback.getSrcSwitchGuard(),
    isScheduleWarmupMode: ctx.isScheduleWarmupMode,
    isWaitingSchedule: ctx.isWaitingSchedule,
    resumeAfterSchedule: ctx.resumeAfterSchedule,
    isReplay: ctx.isReplay,
    replayVideosList: ctx.replayVideosList,
    replayCurrentIndex: ctx.replayCurrentIndex,
    persistReplayProgress: ctx.persistReplayProgress,
    roomGroupType: ctx.roomGroupType,
    liveId: ctx.liveId,
    replayCurrentVideoId: ctx.replayCurrentVideoId,
    roomWatchByDay: ctx.roomWatchByDay,
    pushStatus: ctx.pushStatus,
    playReplayVideoByIndex: (...args) => replayPlayback.playReplayVideoByIndex(...args),
    stopHeartbeat: ctx.stopHeartbeat,
    enterReplayPendingState: (...args) => replayPlayback.enterReplayPendingState(...args),
    setReplayFutureStartTimer: ctx.setReplayFutureStartTimer,
    tryIOSWechatBridgeAutoPlay: ctx.tryIOSWechatBridgeAutoPlay,
    tryIOSWechatBridgeMutedPlay: ctx.tryIOSWechatBridgeMutedPlay,
    resumeVideoPlayback: ctx.resumeVideoPlayback,
    hasPendingUnmute: ctx.hasPendingUnmute,
    hasStoredSoundIntentRestore: ctx.hasStoredSoundIntentRestore,
    scheduleLiveSoundIntentRestore: ctx.scheduleLiveSoundIntentRestore,
    verifySeekResult: (...args) => replayPlayback.verifySeekResult(...args),
    rtcConfig: ctx.rtcConfig,
    isWeChatIOSH5: ctx.isWeChatIOSH5,
    refreshLiveStatusNow: ctx.refreshLiveStatusNow,
    recordPlaybackDebugEvent: ctx.recordPlaybackDebugEvent,
    probePlaybackUrl: ctx.probePlaybackUrl,
    onQualitySample: ctx.onQualitySample,
    playbackErrorVisible: ctx.playbackErrorVisible,
    playbackErrorText: ctx.playbackErrorText,
    createMediaContext: ctx.createMediaContext,
    mediaSourceComponent: ctx.mediaSourceComponent,
    mediaSourceType: ctx.mediaSourceType,
  });
}

/**
 * 播放相关 hooks 的装配层。
 * 职责边界：只连接播放器初始化与录播播放两个子 hook，并暴露 entry 需要的统一方法。
 */
export function useLivePlaybackWiring(ctx) {
  let initVideoPlayer = () => {};
  const replayPlayback = createReplayPlayback(ctx, () => initVideoPlayer);
  const playerInitializer = createPlayerInitializer(ctx, replayPlayback);
  initVideoPlayer = playerInitializer.initVideoPlayer;

  return {
    ...replayPlayback,
    initVideoPlayer,
    switchLiveStreamQuality: playerInitializer.switchLiveStreamQuality,
    handleLivePlayerFailure: playerInitializer.handleLivePlayerFailure,
    markPlaybackReady: playerInitializer.markPlaybackReady,
    retryPlayback: playerInitializer.retryPlayback,
    handleVideoPlayerEnded: playerInitializer.handleVideoPlayerEnded,
  };
}
